//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.ManagerCloud
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagerCloudContextContainer : DbContext
    {
        public ManagerCloudContextContainer()
            : base("name=ManagerCloudContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> ClientSet { get; set; }
        public virtual DbSet<Sale> SaleSet { get; set; }
        public virtual DbSet<Item> ItemSet { get; set; }
        public virtual DbSet<DataSource> DataSourceSet { get; set; }
    }
}
