//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.ManagerCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int ClientId { get; set; }
        public int ItemId { get; set; }
        public double SaleSum { get; set; }
        public int DataSourceId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Item Item { get; set; }
        public virtual DataSource DataSource { get; set; }
    }
}
